<a href="https://colab.research.google.com/github/KryssyCo/DS-Unit-2-Applied-Modeling/blob/master/Krista_Shepard_DSPT2_U2S7M1_Assignment_Applied_Modeling_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Lambda School Data Science, Unit 2: Predictive Modeling

# Applied Modeling, Module 1

You will use your portfolio project dataset for all assignments this sprint.

## Assignment

Complete these tasks for your project, and document your decisions.

- [X] Choose your target. Which column in your tabular dataset will you predict?
- [X] Choose which observations you will use to train, validate, and test your model. And which observations, if any, to exclude.
- [X] Determine whether your problem is regression or classification.
- [X] Choose your evaluation metric.
- [X] Begin with baselines: majority class baseline for classification, or mean baseline for regression, with your metric of choice.
- [X] Begin to clean and explore your data.
- [X] Begin to choose which features, if any, to exclude. Would some features "leak" information from the future?

## Reading

### ROC AUC
- [Machine Learning Meets Economics](http://blog.mldb.ai/blog/posts/2016/01/ml-meets-economics/)
- [ROC curves and Area Under the Curve explained](https://www.dataschool.io/roc-curves-and-auc-explained/)
- [The philosophical argument for using ROC curves](https://lukeoakdenrayner.wordpress.com/2018/01/07/the-philosophical-argument-for-using-roc-curves/)

### Imbalanced Classes
- [imbalance-learn](https://github.com/scikit-learn-contrib/imbalanced-learn)
- [Learning from Imbalanced Classes](https://www.svds.com/tbt-learning-imbalanced-classes/)

### Last lesson
- [Attacking discrimination with smarter machine learning](https://research.google.com/bigpicture/attacking-discrimination-in-ml/), by Google Research, with  interactive visualizations. _"A threshold classifier essentially makes a yes/no decision, putting things in one category or another. We look at how these classifiers work, ways they can potentially be unfair, and how you might turn an unfair classifier into a fairer one. As an illustrative example, we focus on loan granting scenarios where a bank may grant or deny a loan based on a single, automatically computed number such as a credit score."_
- [How Shopify Capital Uses Quantile Regression To Help Merchants Succeed](https://engineering.shopify.com/blogs/engineering/how-shopify-uses-machine-learning-to-help-our-merchants-grow-their-business)
- [Maximizing Scarce Maintenance Resources with Data: Applying predictive modeling, precision at k, and clustering to optimize impact](https://towardsdatascience.com/maximizing-scarce-maintenance-resources-with-data-8f3491133050), by Lambda DS3 student Michael Brady. His blog post extends the Tanzania Waterpumps scenario, far beyond what's in the lecture notebook.
- [Notebook about how to calculate expected value from a confusion matrix by treating it as a cost-benefit matrix](https://github.com/podopie/DAT18NYC/blob/master/classes/13-expected_value_cost_benefit_analysis.ipynb)
- [Simple guide to confusion matrix terminology](https://www.dataschool.io/simple-guide-to-confusion-matrix-terminology/) by Kevin Markham, with video
- [Visualizing Machine Learning Thresholds to Make Better Business Decisions](https://blog.insightdatascience.com/visualizing-machine-learning-thresholds-to-make-better-business-decisions-4ab07f823415)

## This is where I obtained my data.

https://www.apartmentlist.com/rentonomics/rental-price-data/

https://data.world/sya/marijuana-laws-by-state

Updated marijuana laws by state csv with data from 

https://www.governing.com/gov-data/safety-justice/state-marijuana-laws-map-medical-recreational.html
 
and confirmed information on:

https://disa.com/map-of-marijuana-legality-by-state

In [0]:
# Read in csv files and look at top and bottom 5 observations.
import pandas as pd
rent = pd.merge(pd.read_csv('https://raw.githubusercontent.com/KryssyCo/Unit-2-Project/master/Apartment-List-Rent-Data-State_2019-8.csv'),
       pd.read_csv('https://raw.githubusercontent.com/KryssyCo/Unit-2-Project/master/state_marijuana_laws_09_2019%20-%20state_marijuana_laws_10_2016.csv'))
      
print(rent.shape)
rent.head()

(245, 74)

  Location Location_Type  ... recreational_mj_legalized  no_mj_legalization
0  Alabama         State  ...                       NaN                 Yes
1  Alabama         State  ...                       NaN                 Yes
2  Alabama         State  ...                       NaN                 Yes
3  Alabama         State  ...                       NaN                 Yes
4  Alabama         State  ...                       NaN                 Yes

[5 rows x 74 columns]

In [0]:
rent.tail()

    Location Location_Type  ... recreational_mj_legalized  no_mj_legalization
240  Wyoming         State  ...                       NaN                 Yes
241  Wyoming         State  ...                       NaN                 Yes
242  Wyoming         State  ...                       NaN                 Yes
243  Wyoming         State  ...                       NaN                 Yes
244  Wyoming         State  ...                       NaN                 Yes

[5 rows x 74 columns]

## Choose your target. Which column in your tabular dataset will you predict?

The column I choose to use as my target is the column currently labeled " Price_2019_08". I intend on changing the column names to dates and from there, using Panda's to_datetime.

I've done some initial data exploration on the column in the cells below.

In [0]:
# The mean rent for all states as of August 2019 was $1135. The least expensive 
# was $489 and most expensive was $2967
rent['Price_2019_08'].describe()

count     245.000000
mean     1135.395918
std       465.079284
min       489.000000
25%       775.000000
50%      1069.000000
75%      1355.000000
max      2967.000000
Name: Price_2019_08, dtype: float64

In [0]:
# Check columns for NaN's and there are none.
rent['Price_2019_08'].isnull().sum()

0

## Choose which observations you will use to train, validate, and test your model. And which observations, if any, to exclude.

The actaul "observations" for my data are all of the states and the District of Columbia. I may begin by using all of the states and whittle it down to a more manageable number. At this time each state has 5 entries: These include the amount of bedrooms: 

- Studio
- 1 bdrm
- 2 bdrm
- 3 bdrm 
- 4 bdrm

If I do reduce the amount of observations, I will choose an equal amount based on the states current marijuana legalization status as of 08/2019.

I will most likely use a random 80/20 split for my train/val/test split, but cross-validation is also on a back-burner as a possibiliy. 

I considered excluding (Location_type) but I may be adding statewide rental information based on county reporting to see if rents were affected the same way across urban, suburban, and rural counties.

In [0]:
rent['Location'].describe(exclude='number')

count                245
unique                49
top       North Carolina
freq                   5
Name: Location, dtype: object

In [0]:
rent['Location'].value_counts()

## Determine whether your problem is regression or classification.

My problem is a regression problem. I am attempting to predict the quantity of rent paid over time. Since money is continuous variable. 

## Choose your evaluation metric.
I plan use the mean absolute error (MAE) to get my baseline for regression. However, I will explore other options if additional features are added.

A little visualization

In [0]:
# Scatter plot
import plotly.express as px
px.scatter(rent, x='Price_2014_01', y='Price_2019_08', hover_name='Location')

 Begin with baselines: majority class baseline for classification, or mean baseline for regression, with your metric of choice.

 Begin to clean and explore your data.
 
 Begin to choose which features, if any, to exclude. Would some features "leak" information from the future?

In [0]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import RobustScaler, StandardScaler

In [40]:
# Split train into train & val
train, val = train_test_split(rent, train_size=0.80, test_size=0.20,
                              random_state=42)


train.shape, val.shape

((196, 74), (49, 74))

In [0]:

# Use scikit-learn for logistic regression with one feature

# 1. Import the appropriate estimator class from Scikit-Learn
from sklearn.linear_model import LogisticRegression

# 2. Instantiate this class
model = LogisticRegression(solver='sag', multi_class='auto')

# 3. Arrange X features matrix & y target vector
features = ['Price_2014_01']
target = 'Price_2019_08'
X = train[features]
y = train[target]

# 4. Fit the model
model.fit(X, y)

# 5. Apply the model
y_pred = model.predict(X)

In [0]:
# Arrange data into Xfeatures matrix and Y vector
X_train = train[features]
y_train = train[target]

X_val = val[features]
y_val = val[target]

In [52]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score


print('Test Mean Absolute Error Train:', mean_absolute_error(y_train, y_pred))


print('Mean Squared Error Train:', mean_squared_error(y_train, y_pred))


print('Root Mean Squared Error Train:', np.sqrt(mean_squared_error(y_train, y_pred)))


print('R^2 Train:', r2_score(y_train, y_pred))

Test Mean Absolute Error Train: 1162.5969387755101
Mean Squared Error Train: 1544667.9234693877
Root Mean Squared Error Train: 1242.846701516075
R^2 Train: -6.463914667637159